trigger:
- development

pool:
    vmimage: 'ubuntu-latest'

variables:
  IMAGE_REGISTRY_CONNECTION: 'BodAdminSuiteContainers'
  IMAGE_REGISTRY: 'BodAdminSuiteContainers'
  IMAGE_REPOSITORY: 'governanceportal.azurecr.io'
  TAG: 'latest'

stages:
- stage: BuildDockerImage
  jobs:
  - job: BuildPushImage
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: '$(IMAGE_REGISTRY_CONNECTION)'
        repository: '$(IMAGE_REPOSITORY)'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(TAG)'

- stage: DeployDev
  jobs:
  - job: DeployDev
    steps:
    - task: AzureWebAppContainer@1
      inputs:
        azureSubscription: 'Azure subscription 1(e150a27b-e96f-452a-ad3d-35a48a9da39d)'
        appName: 'governanceportaltest'
        containers: 'bodadminsuitecontainers.azurecr.io/governanceportal.azurecr.io:$(TAG)'
